# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:11.2-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
